language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive libicu-dev libxml2-dev libbz2-dev zlib1g-dev 
    - git clone https://github.com/proycon/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
install:
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - git clone https://github.com/proycon/foliatest.git
    - cd foliatest
    - bash bootstrap.sh
    - ./configure
    - make
script: 
    - cd src
    - ln -sf ../tests
    - ./test >&2
    
